# Generated by Django 3.1.7 on 2021-03-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210310_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
