# Generated by Django 3.1.7 on 2021-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.ImageField(default=None, upload_to='thumbnails'),
        ),
    ]
